#!/usr/bin/env python3
"""Generate test_vectors.h from the reference CSV exported by the iris example.

The CSV has one row per test vector: n_inputs input values followed by
n_outputs reference output values, separated by ';'.

Usage: make_test_vectors.py <reference.csv> <test_vectors.h> <n_inputs> <n_outputs>
"""

import sys


def main() -> None:
    if len(sys.argv) != 5:
        sys.exit(__doc__)

    csv_path, header_path = sys.argv[1], sys.argv[2]
    n_inputs, n_outputs = int(sys.argv[3]), int(sys.argv[4])

    rows = []
    with open(csv_path) as csv_file:
        for line in csv_file:
            line = line.strip()
            if not line:
                continue
            values = [float(x) for x in line.split(";")]
            if len(values) != n_inputs + n_outputs:
                sys.exit(f"Row has {len(values)} values, expected {n_inputs + n_outputs}")
            rows.append(values)

    if not rows:
        sys.exit("Reference CSV is empty")

    def c_float(x: float) -> str:
        text = f"{x:.9g}"
        if "." not in text and "e" not in text and "inf" not in text and "nan" not in text:
            text += ".0"
        return text + "f"

    with open(header_path, "w") as header:
        header.write("// Generated by make_test_vectors.py — do not edit.\n")
        header.write("#pragma once\n\n")
        header.write(f"#define NUM_VECTORS {len(rows)}\n")
        header.write(f"#define NUM_INPUTS {n_inputs}\n")
        header.write(f"#define NUM_OUTPUTS {n_outputs}\n\n")
        header.write("static const float test_inputs[NUM_VECTORS][NUM_INPUTS] = {\n")
        for row in rows:
            header.write("    {" + ", ".join(c_float(x) for x in row[:n_inputs]) + "},\n")
        header.write("};\n")

    print(f"Wrote {header_path}: {len(rows)} vectors, {n_inputs} inputs, {n_outputs} outputs")


if __name__ == "__main__":
    main()
