var searchData=
[
  ['quasi_5fnewton_5fmethod_5fpointer',['quasi_Newton_method_pointer',['../struct_open_n_n_1_1_quasi_newton_method_1_1_quasi_newton_method_results.html#a092c0c52bdba31ab3edafc27a8d6d119',1,'OpenNN::QuasiNewtonMethod::QuasiNewtonMethodResults::quasi_Newton_method_pointer()'],['../class_open_n_n_1_1_training_strategy.html#a44fe24c0c4c3b9d19fe996c6418e41aa',1,'OpenNN::TrainingStrategy::quasi_Newton_method_pointer()']]],
  ['quasi_5fnewton_5fmethod_5fresults_5fpointer',['quasi_Newton_method_results_pointer',['../struct_open_n_n_1_1_training_strategy_1_1_results.html#a0043c2bc60a35aeda8cd64f6acf85ef8',1,'OpenNN::TrainingStrategy::Results']]],
  ['quasinewtonmethod',['QuasiNewtonMethod',['../class_open_n_n_1_1_quasi_newton_method.html#abe6c235cd8bc6bdb950540df3fdd98a2',1,'OpenNN::QuasiNewtonMethod::QuasiNewtonMethod(void)'],['../class_open_n_n_1_1_quasi_newton_method.html#a2c3908593e1df0fcda4d20b2da1adf3e',1,'OpenNN::QuasiNewtonMethod::QuasiNewtonMethod(PerformanceFunctional *)'],['../class_open_n_n_1_1_quasi_newton_method.html#ab4ac3a57c1c249211ed35c78565d7563',1,'OpenNN::QuasiNewtonMethod::QuasiNewtonMethod(const tinyxml2::XMLDocument &amp;)']]],
  ['quasinewtonmethod',['QuasiNewtonMethod',['../class_open_n_n_1_1_quasi_newton_method.html',1,'OpenNN']]],
  ['quasinewtonmethodresults',['QuasiNewtonMethodResults',['../struct_open_n_n_1_1_quasi_newton_method_1_1_quasi_newton_method_results.html',1,'OpenNN::QuasiNewtonMethod']]],
  ['quasinewtonmethodresults',['QuasiNewtonMethodResults',['../struct_open_n_n_1_1_quasi_newton_method_1_1_quasi_newton_method_results.html#abd092c0d95f949ae5ceb867d10976cca',1,'OpenNN::QuasiNewtonMethod::QuasiNewtonMethodResults::QuasiNewtonMethodResults(void)'],['../struct_open_n_n_1_1_quasi_newton_method_1_1_quasi_newton_method_results.html#a95e592e7ea36695c98d3b735c3ac2c08',1,'OpenNN::QuasiNewtonMethod::QuasiNewtonMethodResults::QuasiNewtonMethodResults(QuasiNewtonMethod *new_quasi_Newton_method_pointer)']]]
];
