#ifndef BOXPLOT_H
#define BOXPLOT_H

#include <string>

#include "config.h"

using namespace std;
using namespace Eigen;

namespace opennn
{

/// BoxPlot is a visual aid to study the distributions of data_set variables.
/// This structure contains the essentials for making box_plots
/// and obtained the data generated by the box_plot :
/// <ul>
/// <li> Minimum.
/// <li> Maximum.
/// <li> Median.
/// <li> First Quartile.
/// <li> Third Quartile.
/// </ul>

struct BoxPlot {

    type minimum = type(0);

    type first_quartile = type(0);

    type median = type(0);

    type third_quartile = type(0);

    type maximum = type(0);

  // Default constructor.

  explicit BoxPlot() {}

  // Values constructor.

  explicit BoxPlot(const type&, const type&, const type&, const type&, const type&);

  void set(const type&, const type&, const type&, const type&, const type&);
};


}
#endif
