name: Build
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
<<<<<<< HEAD
=======

>>>>>>> 2441909de685001cd371823bfdc5e5c8479b7e60
jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
<<<<<<< HEAD
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
=======
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
>>>>>>> 2441909de685001cd371823bfdc5e5c8479b7e60
      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Install sonar-scanner and build-wrapper
        uses: sonarsource/sonarcloud-github-c-cpp@v3
<<<<<<< HEAD
      - name: Run build-wrapper
        run: |
          build-wrapper-win-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} msbuild sonar_scanner_example.vcxproj /t:rebuild /nodeReuse:false
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }} # Put the name of your token here
        run: |
          sonar-scanner \
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json" \
            --define sonar.inclusions="opennn/opennn/**/*.cpp,opennn/opennn/**/*.h"
=======
      
      - name: Build with build-wrapper (mnist)
        run: |
          build-wrapper-win-x86-64.exe --out-dir build_wrapper_output_directory msbuild examples\mnist\mnist.vcxproj /t:Rebuild /p:Configuration=Release

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          sonar-scanner --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
>>>>>>> 2441909de685001cd371823bfdc5e5c8479b7e60
